# computer_science :
#   first_sem :
#     subjects : 
#       - Environmental science
#       - Ess. of Indian Trad.Knowledge
#       - Mathematics - I
#       - Chemistry
#       - Prog.For Problem Solving
#       - Chemistry Lab
#       - Workshop-Manuf . Process Lab
#       - Prog.For Problem Solving Lab
#     credits :
#       - 0
#       - 0
#       - 4
#       - 4
#       - 3
#       - 1.5
#       - 3
#       - 1
#   second_sem :
#     subjects :
#       - English
#       - Mathematics-II
#       - English Lab
#       - Physics
#       - Engineering Graphics Lab
#       - Physics Lab
#       - Basic Electrical Eng.Lab
#       - Basic Electrical Eng.
#       - Indian Constitution
#     credits :
#       - 2
#       - 4
#       - 1
#       - 4
#       - 3
#       - 1.5
#       - 1
#       - 4
#       - 0
#   third_sem :
#     subjects :
#      - Operations Research
#      - Basic Electronics
#      - Digital Electronics
#      - Data Structures and ALgorithms
#      - Discrete Mathematics
#      - OOP Using Java
#      - Data Struc.And ALgorithms Lab
#      - Advanced Computer Skills Lab
#      - Basic Electronics Lab
#      - OOP Using Java Lab
#     credits :
#      - 3
#      - 3
#      - 3
#      - 3
#      - 3
#      - 3
#      - 1
#      - 1
#      - 1
#      - 1
#   fourth_sem :
#     subjects :
#      - Operating Systems
#      - Operating Systems Lab
#      - Computer Organization
#      - Signals and Systems
#      - Mathematics-III
#      - Computer Organization Lab
#      - Database Management Sys.Lab
#      - Effective Tech.Comm.In English
#      - Finance and Accounting
#      - Database Management Systems
#     credits :
#       - 3
#       - 1
#       - 3
#       - 3
#       - 3
#       - 1
#       - 1
#       - 3
#       - 3
#       - 3
#   fifth_sem :
#     subjects :
#      - COMPUTER NETWORKS LAB
#      - ARTIFICIAL INTELLIGENCE LAB
#      - PRINCIPLES OF PROGRAM.LANG.
#      - Professional Elective –I
#      - ARTIFICIAL INTELLIGENCE
#      - SOFTWARE ENGINEERING
#      - COMPUTER NETWORKS
#      - SOFTWARE ENGINEERING LAB
#      - AUTOMATA LANGUAGES&COMPUTATION
#     credits :
#      - 1
#      - 1
#      - 3
#      - 3
#      - 3
#      - 3
#      - 3
#      - 1
#      - 3
#   sixth_sem :
#     Compiler Design :
#     Design and Analysis of Algorithms :
#     Machine learning :
#     Cryptography and Network Security :
#     Professional Elective –II :
#     Open Elective-I :
#     Machine learning LAB :
#     Design and Analysis of Algorithms Lab :
#     Mini Project :
#     Summer Internship* :
#      - 3
#      - 3
#      - 3
#      - 3
#      - 3
#      - 3
#      - 1
#      - 1
#      - 2
#      - 0